### ISSUE TITLE
Confluent platform incompatibility

### ISSUE THREAD

**Issue by fedefernandez** [fd4s/fs2-kafka#1222]
Hi!

I'm having some binary incompatibilities with the release of the latest modules. 

* fs2-kafka depends on kafka-clients 3.4.0
* fs2-kafka-vulcan depends on kafka-avro-serializer 7.3.3

Given the [Supported Versions and Interoperability for Confluent Platform](https://docs.confluent.io/platform/current/installation/versions-interoperability.html), should `fs2-kafka-vulcan` dependency being upgraded to version 7.4.0?

Confluent Platform | Apache Kafka® | Release Date | Standard End of Support | Platinum End of Support
-- | -- | -- | -- | --
7.4.x | 3.4.x | May 3, 2023 | May 3, 2025 | May 3, 2026
7.3.x | 3.3.x | November 4, 2022 | November 4, 2024 | November 4, 2025

Thanks!

**Comment by OneCricketeer** [comment]
What types of errors are you getting? The Avro serializer hasn't had a breaking change in the client library, to my knowledge

**Comment by OneCricketeer** [comment]
Confluent's documentation is more about support / version mapping, rather than "binary compatibility" of those versions. Until stated otherwise, Kafka and Schema Registry clients clients have largely been forwards/backwards since at least Kafka 0.10.2 and Confluent Platform 4.x, I think, whenever Protobuf/JSONSchema were introduced into the Registry server API
