### ISSUE TITLE
Change to use a single CommittableOffsets construct

### ISSUE THREAD

**Issue by vlovgr** [fd4s/fs2-kafka#233]
There's currently two constructs for committable offsets: 

- [`CommittableOffset`](https://github.com/ovotech/fs2-kafka/blob/0be19fcefab978753d8473af7b3646e515f6eca0/modules/core/src/main/scala/fs2/kafka/CommittableOffset.scala) for committing/accessing a single offset,
- [`CommittableOffsetBatch`](https://github.com/ovotech/fs2-kafka/blob/0be19fcefab978753d8473af7b3646e515f6eca0/modules/core/src/main/scala/fs2/kafka/CommittableOffsetBatch.scala) for committing zero or more offsets.

The idea is to unify these two into a single construct, `CommittableOffsets`. The idea is that it works similarly to `CommittableOffsetBatch`, except when combining two offsets for the same topic-partition, it chooses the highset offset (`CommittableOffsetBatch` simply chooses the right-hand side). This should allow us to form a `Monoid[CommittableOffsets]`, so that we can write:

```scala
offsets.combineAll.commit
```

given `offsets` is `F[CommittableOffsets]` with `Foldable[F]` (most of the time `F` will be `Chunk`).

**Comment by vlovgr** [comment]
Closing this as the `CommittableOffsets` construct cannot provide safe access to a single record offset, which is sometimes desirable.

**Comment by L7R7** [comment]
@vlovgr out of curiosity, can you point me to the places where a single record offset is desirable? I stumbled upon this issue while wondering if it's possible to write a Monoid instance for `CommittableOffset`.
Actually I came from trying to write an Applicative instance for `CommittableConsumerRecord` (which I guess is not possible, even with a Monoid for `CommittableOffset`, because it's impossible to write a correct implementation for `pure`), which is interesting but beyond the scope of this issue.
