### ISSUE TITLE
AdminApiClient deleteTopic doesn't wait for completion.

### ISSUE THREAD

**Issue by paul-snively** [fd4s/fs2-kafka#744]
In fs2-kafka 1.0.3, when I try to use `deleteTopic` on the `AdminApiClient` and then `createTopic`, nondeterministically I will get a failed effect indicating that the topic already exists, i.e. hasn't been deleted by the time `deleteTopic` passes control to the next effect. Looking at the code, this suggests to me that the machinery for supporting `cancelable`, which apparently lifts a `KafkaFuture` to the `F` context with an `Async` constraint, is not working correctly (which frankly seems understandable, since `KafkaFuture` is apparently its own wild-west thing).

**Comment by vlovgr** [comment]
This happens because `deleteTopic` might complete before the change has propagated to all brokers, see [here](https://github.com/apache/kafka/blob/7b379539a5533179b0c86adb352548ac1aa82006/clients/src/main/java/org/apache/kafka/clients/admin/Admin.java#L248). I'm not sure if there's more that can be done except to retry the creation.

**Comment by bplommer** [comment]
I think we could add something about this to the scaladoc.

**Comment by aartigao** [comment]
Since `KafkaFuture` now uses `CompletionStage`, this should be fixed.

I think it's safe to close this 2 year old issue.
